### ISSUE TITLE
FYI Many macOS 10.15.0 sources now available

### ISSUE THREAD

**Issue by follower** [apple-open-source/macos#1]
Thanks for your work on this.

FYI many macOS 10.15.0 sources are now available here: https://opensource.apple.com/release/macos-1015.html

**Comment by mohd-akram** [comment]
Thanks, yeah I saw, but I was waiting a bit for them to put the rest. They seem to be taking their time though so maybe I'll just put what's there in the meantime.

**Comment by mohd-akram** [comment]
Looks like they've added everything now. I'll be updating the repo soon.

**Comment by mohd-akram** [comment]
The repo has been updated.
