### ISSUE TITLE
Consider including "Developer Tools" etc in mirror?

### ISSUE THREAD

**Issue by follower** [apple-open-source/macos#2]
Thanks again for your work on this repository.

Have you considered also including these sections of the site into the repo:

 * "Developer Tools" e.g. https://opensource.apple.com/release/developer-tools-1131.html

 * "iOS"  e.g. https://opensource.apple.com/release/ios-1211.html

 * "OS X Server" e.g. https://opensource.apple.com/release/os-x-server-302.html (Lol, for completeness, I guess. :) )

Thanks for your time.

**Comment by mohd-akram** [comment]
The plan was to do iOS too (see the [meta](https://github.com/apple-open-source/meta) repo), but apparently it's just web stuff. Developer tools seems like it could be useful though. It's not too difficult to add any of them, but I'd need to get the release dates of all those versions for the commit dates to mean anything.

**Comment by follower** [comment]
Maybe the web only iOS stuff is useful to someone? :D

I did a quick search and found this which seems to mention release dates:

 * https://xcodereleases.com/

Even better, apparently they have an API: :)

 * https://xcodereleases.com/data.json

Would that work for the release dates you need?

(I notice they don't include links to opensource.apple.com release in their info/api, maybe we could suggest it. :) )

**Comment by mohd-akram** [comment]
Thanks for the link, that worked great! I've added a commit to the meta repo which allows generating a developer-tools repo. I'll close this issue now and you can open additional ones in the meta repo.
